Doc/readme clas
SAP/abap-file-formats pull request #193
Opened 2021-08-30 09:41 UTC by albertmink

closes #190

2021-08-30 10:16 UTC, wurzka requested changes
There is one (in my opinion) wrong link.

2021-08-30 10:16 UTC, wurzka commented on file-formats/clas/README.md
> +`<name>.clas.texts.<lang>.properties` | 0...n | [Text Elements](https://help.sap.com/viewer/c238d694b825421f940829321ffa326a/7.40.19/en-US/4ec6cf916e391014adc9fffe4e204223.html) | - | [`zcl_aff_examp
Here, the example of text elements links to the testclasses.

2021-08-30 11:22 UTC, wurzka approved these changes
Thanks, LGTM

2021-08-30 11:56 UTC, huber-nicolas commented on file-formats/clas/README.md
> +`<name>.clas.definition.abap` | 0...1 | | - | [`zcl_aff_example.clas.definitions.abap`](./examples/zcl_aff_example.clas.definitions.abap)
<name>.clas.definition.abap
should be
<name>.clas.definition**S**.abap

2021-08-31 06:21 UTC, albertmink commented on file-formats/clas/README.md
> +`<name>.clas.definition.abap` | 0...1 | | - | [`zcl_aff_example.clas.definitions.abap`](./examples/zcl_aff_example.clas.definitions.abap)
Implement suggestion from @huber-nicolas 
```suggestion
`<name>.clas.definitions.abap` | 0...1 | | - | [`zcl_aff_example.clas.definitions.abap`](./examples/zcl_aff_example.clas.definitions.abap)
```

2021-08-31 06:23 UTC, merged