CHKO: Change remoteEnabled flag to checkType enum
SAP/abap-file-formats pull request #275
Opened 2021-12-16 10:39 UTC by burcuka

2021-12-16 11:49 UTC, schneidermic0 approved these changes
Looks good to me

2021-12-16 13:11 UTC, albertmink commented
And removes 'technical_id' :)

2021-12-16 13:53 UTC, albertmink commented on file-formats/chko/type/zif_aff_chko_v1.intf.abap
> +      "! Remote Enabled
```suggestion
      "! Remote enabled
```

2021-12-16 13:53 UTC, albertmink commented on file-formats/chko/type/zif_aff_chko_v1.intf.abap
> +    "! Check Type
```suggestion
    "! Check type
```

2021-12-16 13:53 UTC, albertmink commented on file-formats/chko/type/zif_aff_chko_v1.intf.abap
> +  "! Check Type
```suggestion
  "! Check type
```

2021-12-16 13:55 UTC, albertmink requested changes
The descriptions are non-titlecase.

2021-12-17 10:39 UTC, albertmink requested changes
Ahh, I found another case miss match 😇

2021-12-17 10:39 UTC, albertmink commented on file-formats/chko/type/zif_aff_chko_v1.intf.abap
> +      "! <p class="shorttext">Is hidden</p>
```suggestion
      "! <p class="shorttext">Is Hidden</p>
```

2021-12-17 10:39 UTC, albertmink commented on file-formats/chko/chko-v1.json
> +            "title": "Is hidden",
```suggestion
            "title": "Is Hidden",
```

2021-12-17 10:39 UTC, albertmink approved these changes

2021-12-20 08:38 UTC, merged