update sajc
SAP/abap-file-formats pull request #421
Opened 2022-11-02 17:09 UTC by huber-nicolas

2022-11-04 08:24 UTC, wurzka requested changes
See my comment

2022-11-04 08:24 UTC, wurzka commented on file-formats/sajc/type/zif_aff_sajc_v1.intf.abap
> +    "! <p class="shorttext">General Information</p>
I think we talked about this before a while: We do not want object typer owner to have "General Information" in their AFF type/schema. When they want to have it as section title in their editor, they have to add it to their configuration. So I would update this here.

2022-11-15 14:29 UTC, schneidermic0 requested changes
Sorry, @huber-nicolas. I just found some more issues :(

2022-11-15 14:29 UTC, schneidermic0 commented on file-formats/sajc/type/zif_aff_sajc_v1.intf.abap
> +      report_name           TYPE ty_report_name,
I just came across "report". Can we change this to "program"? As far as I can see in SAPterm. "report" is the obsolete term for "executable program".
```suggestion
      "! <p class="shorttext">Executed Program</p>
      "! Name of the program which is executed within the job
      program_name           TYPE ty_report_name,
```

2022-11-15 14:36 UTC, huber-nicolas commented on file-formats/sajc/README.md
> +`<name>.sajc.json` | 1 | [`zif_aff_sajc_v1.intf.abap`](./type/zif_aff_sajc_v1.intf.abap) |[`sajc-v1.json`](./sajc-v1.json) | [`z_aff_example_sajc.sajc.json`](./examples/z_aff_example_sajc.sajc.json)
yes this can be reverted

2022-12-06 11:56 UTC, wurzka approved these changes

2022-12-06 15:35 UTC, schneidermic0 approved these changes
Looks good to me

2022-12-06 15:37 UTC, merged