Feature/gsmp
SAP/abap-file-formats pull request #451
Opened 2022-12-07 10:14 UTC by mseich

Add Instance Creation Mode

2022-12-07 13:43 UTC, schneidermic0 commented
Just a heads-up. We have a similar property (like `instanceCreationMode`) for BAdI definitions:

https://github.com/SAP/abap-file-formats/blob/c83d2cfecc48ad77049986d52477179638dfe5ae/file-formats/enhs/enhs-v1.json#L119-L138

Would it make sense to use the same values for both?

2022-12-08 07:27 UTC, wurzka requested changes
Looks good to me, but could you also please update the example for GSMP? It should be enough to add the line 
`"instanceCreationMode": "create",`
between those
https://github.com/SAP/abap-file-formats/blob/652d7830a4ccac0980c66d2a5b1f07884297f221/file-formats/gsmp/examples/z_aff_example_gsmp.gsmp.json#L13-L14

2022-12-08 08:44 UTC, schneidermic0 commented
Addition to my comment above with a proposal to use the same terms in GSMP and ENHS.

We could use the field `instantiation` for GSMP and ENHS with the values `createNew` and `reuse` (for BAdIs we add `contextSpecific`). 

I have no clear opinion about the names. Other proposals are welcome.

@mseich @marcushoepfner What do you think?

2022-12-08 09:18 UTC, mseich commented
createNew and reuse would be OK for me. I'll discuss this with the team. Eventually we will add possible values to the instantiation field later like 'adaptive'. In that case ENHS and GSMP would drift apart anyway.

2022-12-12 09:34 UTC, wurzka commented on file-formats/gsmp/type/zif_aff_gsmp_v1.intf.abap
> +      create      TYPE ty_instantiation VALUE 'C',
Since we decided on 'createNew', shouldn't it be 
```suggestion
      create_new      TYPE ty_instantiation VALUE 'C',
```
?

2022-12-12 13:58 UTC, schneidermic0 commented
> @marcushoepfner What do you think?

I have talked to @marcushoepfner earlier today. He agrees to adapt the enum values for ENHS

2022-12-12 14:01 UTC, schneidermic0 approved these changes
Looks good to me.

Thank you @mseich for keeping the file format up-to-date. 👍

2022-12-12 14:06 UTC, wurzka approved these changes
Thanks, looks good to me!

2022-12-12 14:09 UTC, merged