[RONT] Add ODM Entity Name and Interface Behavior Definition to RONT AFF
SAP/abap-file-formats pull request #589
Opened 2024-02-27 14:25 UTC by Ehret-Thomas

The AFF interface for SAP Object Type (RONT) is extended by two new optional fields:
* interface_behavior_definition
* odm_entity_name

These fields make it possible to relate an existing SAP Object Type to a One Domain Model (ODM) entity and / or [Interface Behavior Definition](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/abenbdl_rap_bo_interface.htm?file=abenbdl_rap_bo_interface.htm), thus enriching the SAP Object Type's integration possibilities.

2024-02-28 09:23 UTC, wurzka requested changes
Hi @Ehret-Thomas, thanks for updating the file format. We had a look from UX point of view. Please see my comment.

2024-02-28 09:23 UTC, wurzka commented on file-formats/ront/type/zif_aff_ront_v1.intf.abap
> +      interface_behavior_definition TYPE c LENGTH 30,
We struggled with the term Interface Behavior Definition. Is it a special interface or a special behavior definition? For us, it sounds very technical. But we may need more input on this field.

2024-02-28 09:23 UTC, wurzka commented on file-formats/ront/type/zif_aff_ront_v1.intf.abap
> +      odm_entity_name               TYPE c LENGTH 255,
Is ODM a common abbreviation or would it be better to use One Domain Model for the title and component name?
We also recommend not to use `name` therefore our suggestion would be
```suggestion
      "! <p class="shorttext">One Domain Model Entity</p>
      "! The One Domain Model entity related to the SAP Object Type.
      one_domain_model_entity               TYPE c LENGTH 255,
```
or alternatively with the abbreviation:
```suggestion
      "! <p class="shorttext">ODM Entity</p>
      "! The One Domain Model entity related to the SAP Object Type.
      odm_entity               TYPE c LENGTH 255,
```

2024-02-28 09:29 UTC, schneidermic0 commented
Usually, we don't recommend to put fields on top-level anymore. However, since this would require an increase of the format version I think we should keep the structure as suggested by @Ehret-Thomas

2024-03-01 09:24 UTC, albertmink commented
Checked the terms and their context. This are kind of standard expressions/names in RAP, resp. DOM context.

2024-03-01 09:25 UTC, albertmink approved these changes
LGTM

2024-03-01 13:30 UTC, merged