[EDCR] Add new object type for EDCR
SAP/abap-file-formats pull request #630
Opened 2024-07-05 05:01 UTC by KUMARMUKULSAP

2024-07-08 13:10 UTC, GuilhermeSaraiva96 commented
Hi,

Maybe the Pull Request is not yet review-ready, but the AFF contains no information, except for the type name. Is this on purpose?

2024-07-22 13:07 UTC, GuilhermeSaraiva96 requested changes
Requesting changes so that my last question is clarified

2024-08-11 16:51 UTC, KUMARMUKULSAP commented
There are no additional attributes to this object, we only need description of the object

2024-08-14 08:13 UTC, Markus1812 requested changes
Thank you for your AFF type. Please delete the .DS_Store file and add an example with the name `z_aff_example_edcr.edcr.json`, even though its nearly empty. Remember to link it in the README.md.

2024-08-14 08:13 UTC, Markus1812 commented on file-formats/edcr/type/zif_aff_edcr_v1.intf.abap
> +    "! Representation Type (EDCR) v1
```suggestion
    "! Representation type
```
Please use sentence case in descriptions as described in our [wiki](https://github.com/SAP/abap-file-formats/blob/main/docs/json.md#description).

2024-08-28 09:16 UTC, KUMARMUKULSAP commented
> Thank you for your AFF type. Please delete the .DS_Store file and add an example with the name `z_aff_example_edcr.edcr.json`, even though its nearly empty. Remember to link it in the README.md.

2024-08-28 15:09 UTC, Markus1812 commented
Thank you for adapting our suggestions. We have fixed all line endings of the example and README file and added a new line at the end of file. 

All checks except Contributor License Agreement are now fulfilled. If you could please check the [first comment](https://github.com/SAP/abap-file-formats/pull/630#issuecomment-2210175758) and perform the necessary actions.

2024-08-29 01:37 UTC, KUMARMUKULSAP commented
@Markus1812 : I have signed the CLA agreement.

2024-09-26 14:17 UTC, wurzka approved these changes
Looks good to me.

2024-09-27 08:08 UTC, GuilhermeSaraiva96 approved these changes

2024-09-27 08:48 UTC, wurzka approved these changes

2024-09-27 08:48 UTC, merged