[NTTA] Remove implementation exit
SAP/abap-file-formats pull request #631
Opened 2024-07-09 09:39 UTC by thomas-kaltenbach

Field "implementation exit" is not needed anymore. 
Created new aff version of ntta.

2024-07-15 12:13 UTC, huber-nicolas commented on file-formats/ntta/README.md
> +`<name>.ntta.json` | 1 | [`zif_aff_ntta_v2.intf.abap`](./type/zif_aff_ntta_v1.intf.abap) | [`ntta-v2.json`](./ntta-v1.json) | [`z_aff_example_ntta.ntta.json`](./examples/z_aff_example_ntta.ntta.json)
Can you please do 2 tables in the readme as it is done for [ SITO](https://github.com/SAP/abap-file-formats/tree/main/file-formats/sito).

2024-07-15 12:14 UTC, huber-nicolas commented
Can you please add an example object for v2?

2024-07-15 12:15 UTC, huber-nicolas requested changes
Please see my 2 comments

2024-07-16 10:54 UTC, thomas-kaltenbach commented
> Please see my 2 comments

done

2024-07-17 08:19 UTC, huber-nicolas approved these changes

2024-07-17 08:24 UTC, huber-nicolas commented
Since this Abap File Format is not yet productively used we can still update the version 1 compatibly.

2024-07-17 08:25 UTC, merged